### ISSUE TITLE
기본 템플릿 구상 및 구현

### ISSUE THREAD

**Issue by N0N4M3D-b** [hoseCloud/sp1-frontend#2]
ㅈㄱㄴ

**Comment by hoseCloud** [comment]
아래 스크린을 목표로 첫 screen 제작.
무지성 코딩, 피드백 환영.

![슬라이드1](https://user-images.githubusercontent.com/102496441/161274807-4a194b0d-22e4-4352-a433-dd52626399f9.PNG)

**Comment by hoseCloud** [comment]
#3

**Comment by hoseCloud** [comment]
풀리퀘 코드 화면, 기능은 없음.

![2](https://user-images.githubusercontent.com/102496441/161421830-9b60e1e9-52fa-4bcd-aac4-c6b40351cda6.png)
